# Miniproject

You have to turn in

* a file 

  >`mp_apellidos.ipynb` 
  
  where `apellidos` are the last names of the members of each team.Just fill in the cell codes below with your functions and run the lines that currently start with comments. Make sure it works fine by executing Kernel/Restart & Run All.
  
  **Don't forget to write function docstrings and an adequate control of function parameters.** 
    
    
* a file 
  
  >`mp_apellidos.html` 
  
  with an `html` rendering of the previous `.ipynb` file (for instance, if working with Jupyter notebooks, just apply `File / Download as HTML` after a correct run of `Kernel/Restart & Run All`).

**Submitting your work**

1. Create a folder named `apellidos` and place there the previous `.ipynb`and `.html` files.
2. Compress **the folder** with 7zip, WinZip or a similar tool to create a `apellidos.zip` compressed file.
3. Upload this zipped file using the moodle link.

**Very important!!!**

*Make sure you follow the file naming conventions above*. If not, you may be asked to resubmit your work.



## Question 1: Finding the Longest Common Subsequence

We have not paid too much attention to it, but we have in the slides the basis of a dynamic programming algorithm to find the length of **longest common subsequence** between two strings, i.e. the longest, perhaps non consecutive, string that appears in both.  

Notice that **we do not impose** the constraint of the **characters in the sequence be consecutive**; with that requirement the problem is called the **common substring problem**.

Write first a Python function `lcs_matrix(s, t)` that receives two strings `s, t` and returns the dynamic programming matrix used to compute the length of their longest common subsequence.

Then write a Python function `lcs(s, t)` that returns a string with a longest common subsequence, using the LCS matrix returned by the previous function.

In [2]:
import numpy as np

t = "biscuit"
s = "suitcase"

def lcs_matrix(s, t):
    """
    Constructs the dynamic programming matrix for computing 
    the longest common subsequence (LCS) between two sequences.

    The matrix is initialized with zeros and updated using the LCS algorithm, 
    where each cell contains the length of the longest common subsequence 
    found up to that point.

    Args:
        s (str): The first input sequence.
        t (str): The second input sequence.

    Returns:
        matrix: the calculated LCS matrix.
    """

    matrix = np.zeros((len(s)+1, len(t)+1), dtype = int) # +1 is used to initialize
                                                         # the matrix in 0's
    for i in range(1, len(s)+1):
        for j in range(1, len(t)+1):
            if s[i-1] == t[j-1]:                    # If the characters match
                matrix[i][j] = matrix[i-1][j-1] + 1 # take diagonal and add 1
            else:                                   
                matrix[i][j] = max(matrix[i-1][j], matrix[i][j-1]) # Take the max
                                        # between the results at the top or left
    return matrix


def longestCommonSubsequence(s, t):
    """
    Computes the longest common subsequence (LCS) between two given strings.

    The function constructs the LCS matrix using `lcs_matrix()` function and 
    then traces back from the bottom-right corner to reconstruct the LCS.

    Args:
        s (str): The first input string.
        t (str): The second input string.

    Returns:
        str: The longest common subsequence.
    """

    matrix = lcs_matrix(s, t)
    i, j = len(s), len(t)
    subsequence = []
    
    while i > 0 and j > 0: # Hasta que llegemos a la primera fila/columna
        if s[i-1] == t[j-1]:
            subsequence.append(s[i-1])
            i -= 1
            j -= 1
        elif matrix[i-1][j] > matrix[i][j-1]:  # Mover hacia arriba
            i -= 1
        else:  # Mover hacia la izquierda
            j -= 1
    
    return ''.join(reversed(subsequence))  # Se invierte la lista porque se llenó al revés


test_cases = [
    ("biscuit", "suitcase"),
    ("bananas", "bahamas"),
    ("confidential", "trascendental")
]

for s, t in test_cases:
    print(f"LCS({s}, {t}) = '{longestCommonSubsequence(s, t)}'")

LCS(biscuit, suitcase) = 'suit'
LCS(bananas, bahamas) = 'baaas'
LCS(confidential, trascendental) = 'cndental'


## Question 2: The Pascal Triangle

Pascal's triangle is a triangular array of integers constructed with the following formula:

* The first row consists of the number 1.
* For each subsequent row, each element is the sum of the numbers directly above it, on either side.

For example, here are the first few rows:  
```text 
    1  
   1 1  
  1 2 1  
 1 3 3 1  
1 4 6 4 1 
``` 

Write a Python function `pascal_row(k)` that returns the `k`-th row of Pascal's triangle. Assume the single `1` to be the 0-th row.  

*Hint: Make it a recursive function that computes first the previous row `k-1` and uses it to compute the current one.*

In [5]:
def pascal_row(k):
    """
    Compute the k-th row of Pascal's Triangle using recursion.
    
    Pascal's Triangle is a triangular array where each entry is the sum of the 
    two directly above it. This function recursively constructs each row based 
    on the previous row.
    
    Args:
        k (int): The row index (zero-based) to compute.
    
    Returns:
        list: A list containing the elements of the k-th row of Pascal's Triangle.
    """
    if k == 0:
        return [1]  # La primera linea del triangulo de Pascal

    previous_row = pascal_row(k - 1)  # Computar recursivamente la fila anterior
    

    def build_row(prev, i=0):
        """
        Recursively construct the middle elements of Pascal's Triangle row.

        Args:
            prev (list): The previous row of Pascal's Triangle.
            i (int): The current index for computing adjacent sums.

        Returns:
            list: The computed middle elements of the row.
        """
        if i == (len(prev) - 1):
            return []  # Parar cuando se llegue al último elemento  
        return [prev[i] + prev[i+1]] + build_row(prev, i+1)  # sumar elementos adjacentes
    
    return [1] + build_row(previous_row) + [1]  # Construir la nueva fila usando recursion


for k in range(11):
    print(pascal_row(k))


[1]
[1, 1]
[1, 2, 1]
[1, 3, 3, 1]
[1, 4, 6, 4, 1]
[1, 5, 10, 10, 5, 1]
[1, 6, 15, 20, 15, 6, 1]
[1, 7, 21, 35, 35, 21, 7, 1]
[1, 8, 28, 56, 70, 56, 28, 8, 1]
[1, 9, 36, 84, 126, 126, 84, 36, 9, 1]
[1, 10, 45, 120, 210, 252, 210, 120, 45, 10, 1]


## Question 3: The 0-1 Knapsack Problem

As a sideline to our studies we are considering entering the bank robbing business, for which we must be able to solve the following problem: if we have a knapsack which stands a total integer weight of $W$ and there are $n$ items in the bank's vault with integer values $v_i$ and weights $w_i$, how do we choose those that maximize our loot without breaking the knapsack? Recall that we are in a 0-1 situation: you either take the entire item or none at all.

A greedy strategy (natural under the circumstances!) is to order the items by descending relative values $\frac{v_i}{w_i}$ and add them to the knapsack until the allowed total weight $W$ is surpassed. Remember that you cannot take cannot take a fraction of an item.

Write a function `greedy_value(l_weights, l_values, max_weight)` that returns the value of the maximal loot made up of elements with weights in `l_weights` and values in `l_values` that can be carried away in a knapsack which can hold at most a weight `max_weight`. 

In [6]:
def greedy_value(l_weights, l_values, max_weight):
    """
    """

    # Calculamos el valor relativo de cada item
    rel_val = []
    for v, w in zip(l_values, l_weights):
        rel_val.append(v/w)
    
    # Añadimos los valores relativos y ordenamos las listas por valor relativo
    values = (zip(l_values, l_weights, rel_val))

    # Tenemos v_i, w_i, rv_i por cada item
    # Para el mayor valor relativo, si el weight entra en la saca meter,
    # para el sig valor, si el weight entra meter, sino probar el sig
    # para el sig valor, si el weight entra meter, sino probar el sig más peq

    totalW_added = 0
    totalV_added = 0
    for v, w, _ in values:
        if (w + totalW_added) < max_weight:
            totalW_added += w
            totalV_added += v
    return totalW_added, totalV_added

## Testing values
l_values  = [15, 10, 11]
l_weights = [5, 4, 4]
max_weight = 8


weight, value = greedy_value(l_weights, l_values, max_weight)
print(f"Total weight: {weight}\nTotal value: {value}")

Total weight: 5
Total value: 15


## Question 4: Dynamic Programming to Solve the 0-1 Knapsack Problem

Looking at the output of your greedy function on the previous example, you should be aware that your greedy strategy won't always give an optimal loot.
But don't worry, Dynamic Programming comes to the rescue!

Devise a dynamic programming strategy to maximize the loot and explain it in this markdown cell.

Then, write in the next cell a Python function `optimal_value(l_weights, l_values, max_weight)` that returns the value of the maximal loot made up of elements with weights in `l_weights` and values in `l_values` that can be carried away in a knapsack which can hold at most a weight `max_weight`. 

In [7]:
import numpy as np

def optimal_value(l_weights, l_values, max_weight):
    """ 
    Builds the dynamic programming matrix to solve the Knapsack problem 
    and reconstructs the optimal set of items.

    Args:
        l_weights (list[int]): List of item weights.
        l_values (list[int]): Corresponding list of item values.
        max_weight (int): Maximum weight capacity of the knapsack.

    Returns:
        tuple:
            - value_matrix (np.ndarray): Matrix storing computed max values.
            - max_value (int): Maximum obtainable value.
            - selected_items (list[int]): List of selected item indices.
                Returns:
    """
    
    # Error handling:
    if len(l_weights) != len(l_values):
        raise ValueError("Mismatch: weight and value lists must have the same length.")
    
    if not l_weights or max_weight == 0:
        return np.zeros((1, max_weight + 1), dtype=int), 0, []

    else:
        # El tamaño de la matriz es:
        # el numero de elementos que tenemos +1 (para añadir la fila de 0's)
        # por el peso total +1 (para añadir la columna de 0's)
        num_items = len(l_weights)
        value_matrix = np.zeros((num_items + 1, max_weight + 1), dtype=int)
        
        # Build the matrix
        for i in range(1, num_items + 1):
            for w in range(max_weight + 1):
                if l_weights[i - 1] <= w: # Si el peso del elemento entra en el saco:
                    value_matrix[i][w] = max(value_matrix[i - 1][w], 
                                            l_values[i - 1] + value_matrix[i - 1][w - l_weights[i - 1]])
                                        # Coger el max entre el valor de la posicion i-1,w
                                        # y el valor del elemento + el valor en la posición i-1, w = w - l_weights[i-1]
                else:
                    value_matrix[i][w] = value_matrix[i - 1][w]
            
        # The maximum value is at value_matrix[num_items][max_weight]
        max_value = value_matrix[num_items][max_weight]

        # Backtracking to find selected items
        selected_items = []
        w = max_weight
        for i in range(num_items, 0, -1): # To iterate backgwards from the last item to the first
            if value_matrix[i][w] != value_matrix[i - 1][w]:  # If the value changed compared to that on top, the item was included
                selected_items.append(i - 1)  # Store item index
                w -= l_weights[i - 1]  # Reduce weight capacity

        selected_items.reverse()  # Reverse for correct order

        return value_matrix, max_value, selected_items


# Test Example
l_weights = [4, 4, 5]
l_values  = [10, 11, 15]
max_weight = 8

value_matrix, max_value, selected_items = optimal_value(l_weights, l_values, max_weight)

print("Optimal Value:", max_value)
print(f"""The items that allow a maximum loot are items which 
      correspond to the weights, values: {[(l_weights[i], l_values[i]) for i in selected_items]}""")
print("The resulting matrix to compute this was: \n", value_matrix)


Optimal Value: 21
The items that allow a maximum loot are items which 
      correspond to the weights, values: [(4, 10), (4, 11)]
The resulting matrix to compute this was: 
 [[ 0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 10 10 10 10 10]
 [ 0  0  0  0 11 11 11 11 21]
 [ 0  0  0  0 11 15 15 15 21]]


In [ ]:
############################################### ANEXO I ################################################
### Explicación de las funciones en detalle:


######################## Question 1: Finding the Longest Common Subsequence ############################
def lcs_matrix(seq1, seq2):
    """
    Explicación de la función, argumentos y que se obtiene de ella.
    """
    matrix=np.zeros((len(s)+1,len(t)+1), dtype = int)
    ## Creamos una matriz de 0's para rellenar con el largo de las cadenas s y t 
    # len+1 -> Agrandamos 1 para crear la iniciacion en 0 de la matriz 
    # para el cálculo de la cadena vacía
    
    for i in range(1, len(s)+1):      
    ## Rango, desde 1, para dejar la linea de 0's intacta, y hasta el largo de la cadena +1
    # para que continue más allá del rango 7,8, que para python significa parar en las 
    # posiciones 6,7

        for j in range(1, len(t)+1):  
        ## Separamos en dos bucles: for i in range...//for j in range... para que itere sobre el 
        # i=1 y j=1,2,3..., luego el i=2, j=1,2,3... y vaya revisando caracter por caracter
                                      
            if s[i-1] == t[j-1]:    
            ## Si el caracter en s[a la posicion iterada] coincide con el caracter en 
            # t[a la posicion iterada] (proceder a:) 
            
            # Nota: Usamos rango de la palabra i-1, j-1 porque hemos empezado con i,j=1, 
            # pero las palabras se indexan desde 0 en python

                matrix[i][j] = matrix[i-1][j-1] + 1
                ## Para la posición actual (i,j) de la matriz el valor cambia a ese 
                # de la posicion i-1 y j-1, sumandole +1

            else: 
            # Si el caracter no coincide (proceder a:)

                matrix[i][j] = max(matrix[i-1][j], matrix[i][j-1])
                ## Para la posición actual (i,j) de la matriz el valor cambia a el más alto
                # entre la posicion i-1,j y i,j-1

    return matrix
    # Devolvemos el resultado de la matriz calculada


def longestCommonSubsequence(s, t):
    """
    Explicación de la función, argumentos y que se obtiene de ella.
    """

    matrix = lcs_matrix(s, t)
    # Llamamos la funcion anterior para crear la matriz que tenemos que seguir 
    i, j = len(s), len(t)
    # Definimos el tamaño máx de los indices i y j para poder empezar desde el final
    # de la matriz, la ultima columna y fila
    subsequence = []
    # Creamos una lista vacía para añadir los elementos en común que vamos encontrando
    
    while i > 0 and j > 0: 
    # Hasta que llegemos a la primera fila/columna
        if s[i-1] == t[j-1]:
        # Que hacer si los caracteres son iguales:
            subsequence.append(s[i-1])
            # Añadimos el caracter a la lista de subsecuencias
            i -= 1
            j -= 1
            # Modificamos los indices para movernos a la diagonal
        elif matrix[i-1][j] > matrix[i][j-1]:  
        # Si los caracteres son distintos y el resultado de arriba en la matriz es mayor que
        # el de la izquierda
            i -= 1 
            # Mover hacia arriba
        else:  
        # Sino mover hacia la izquierda
            j -= 1
    
    return ''.join(reversed(subsequence))  
    # Se invierte la lista porque se llenó al revés



################################# Question 2: The Pascal Triangle #####################################

def pascal_row(k):
    """
    Explicación de la función, argumentos y que se obtiene de ella.
    """

    if k == 0:
        return [1]  # The first row of Pascal’s Triangle

    previous_row = pascal_row(k - 1)  # Recursively compute the previous row
    

    def build_row(prev, i=0): 
    # Cada vez que la llamamos reiniciamos i en 0, para usarla como indice

        if i == (len(prev) - 1): 
            return []  
        # Stop when reaching the last element
        
        return [prev[i] + prev[i+1]] + build_row(prev, i+1)  
        # Returns the sum of adjacent elements
    

    return [1] + build_row(previous_row) + [1]  
    # By using build_row we can reconstruct the intermediate part based on the 
    # previous row
